test_task_news/news_main/urls.py
from django.urls import path

from .views import IndexView, NewsView, ContactView, AboutView, FeedbackView, NewsCreateView, \
    NewsUpdateView, delete_view

app_name = 'news_main'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('news/', NewsView.as_view(), name='news'),
    path('contact/', ContactView.as_view(), name='contacts'),
    path('about/', AboutView.as_view(), name='about'),
    path('feedback/', FeedbackView.as_view(), name='feedback'),
    path('news-add/', NewsCreateView.as_view(), name='news_add'),
    path('news-edit/<int:pk>/', NewsUpdateView.as_view(), name='news_edit'),
    path('news_delete/<int:pk>', delete_view, name='news_delete')
]

test_task_news/test_task_news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news_main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_task_news/news_main/models.py
from django.db import models


class News(models.Model):
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    description = models.TextField(max_length=500, verbose_name='Описание')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    views = models.IntegerField(verbose_name='Просмотры', default=0)

    def __str__(self):
        return self.title


class Comment(models.Model):
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    text = models.TextField(max_length=500, verbose_name='Сообщение')

    def __str__(self):
        return self.text

test_task_news/news_main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView

from .models import News


class IndexView(ListView):
    """ Главная страница"""
    template_name = 'index.html'
    model = News
    queryset = News.objects.all().order_by('-views')[:5]
    context_object_name = 'news'


class NewsView(ListView):
    """ Страница новостей"""
    template_name = 'news_main/news.html'
    model = News
    queryset = News.objects.all().order_by('-created_at')
    context_object_name = 'news'


class ContactView(ListView):
    """ Страница контактов """
    template_name = 'news_main/contacts.html'
    queryset = []


class AboutView(ListView):
    """ Страница о нас """
    template_name = 'news_main/about.html'
    queryset = []


class FeedbackView(ListView):
    """ Страница обратной связи """
    template_name = 'news_main/feedback.html'
    queryset = []


class NewsCreateView(CreateView):
    """ Создание новой новости """
    model = News
    template_name = 'news_main/add_news.html'
    success_url = '/'
    fields = ['title', 'description']


class NewsUpdateView(UpdateView):
    """ Редактирование новости """
    model = News
    template_name = 'news_main/update_news.html'
    success_url = '/'
    fields = ['title', 'description']


def delete_view(request, pk):
    """ Удаление новости """
    context = {}
    obj = get_object_or_404(News, pk=pk)
    if request.method == "POST":
        obj.delete()
        return HttpResponseRedirect("/")

    return render(request, "news_main/delete_view.html", context)

test_task_news/news_main/templates/index.html
{% extends 'news_main/base.html' %}
{% load static %}
{% block content %}
        <div class="content__info">
            <h2 class="info__header">Privacy Policy</h2>
            <p class="main__text">When you’re ready to go beyond prototyping in Figma, 
                Webflow’s ready to help you bring your </p>
        </div>
        {% for new in news %}
        <div class="news">
            <h4 class="news__header">{{ new.title }}</h4>
            <p class="main__text">{{ new.description }}</p>
            <div class="news__date">
                <div class="news__date_created">Дата создания: {{ new.created_at|date:"M d, Y" }}</div>
                <div class="news__date_updated">Дата обновления:{{ new.updated_at|date:"M d, Y"  }}</div>
                <div class="news__watch">Просмотры: {{ new.views }}</div>
            </div>
            {% for comm in new.comment_set.all %}
            <div class="news__comment_block">
                <div class="comment">{{ comm.text }}</div>
                <div class="comment__date">{{ comm.created_at|date:"M d, Y"  }}</div>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
{% endblock content %}

test_task_news/news_main/templates/news_main/about.html
{% extends 'news_main/base.html' %}
{% load static %}
{% block content %}
<div class="content">
    <div class="about__as__block">
        <div class="about__info">
            <h6 class="about__header">About as</h6>
            <h2 class="about__title">Our designs solve problems</h2>
            <p class="main__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do 
                    eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                    Ut enim ad minim veniam.</p>
        </div>
        <div class="about__logo">
            <img class="about__img" src="{% static 'img/about_as.jpeg' %}" alt="">
        </div> 
    </div>
    <div class="block__who__we">
        <div class="who__we__tap">
            <div class="who__we__title">Goal focussed</div>
            <p class="main__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                Ut enim ad minim veniam, quis nostrud exercitation ullamco 
                laboris nisi ut aliquip ex ea commodo consequat.</p>
        </div>
        <div class="who__we__tap">
            <div class="who__we__title">Continuous improvement</div>
            <p class="main__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                Ut enim ad minim veniam, quis nostrud exercitation ullamco 
                laboris nisi ut aliquip ex ea commodo consequat.</p>
        </div>
    </div>
    <img class="whe__we__img" src="{% static 'img/who_we.jpeg' %}" alt="">
    <div class="our__mission__block">
        <div class="our__mission__tap">
            <div class="our__mission__info">
                <p class="our__mission__header">Our Mission</p>
                <div class="our__mission__title">Inspire, Innovate, Share</div>
                <p class="main__text">Lorem ipsum dolor sit amet, consectetur 
                    adipiscing elit, sed do eiusmod tempor incididunt ut labore et 
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud 
                    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            </div>
            <img class="our__mission__img" src="{% static 'img/man_in_office.jpeg' %}" alt="">
        </div>
        <div class="our__mission__tap">
            <img class="our__mission__img" src="{% static 'img/man_in_office.jpeg' %}" alt="">
            <div class="our__mission__info">
                <p class="our__mission__header">Our Vision</p>
                <div class="our__mission__title">Laser focus</div>
                <p class="main__text">Lorem ipsum dolor sit amet, 
                    consectetur adipiscing elit, sed do eiusmod tempor incididunt ut 
                    labore et dolore magna aliqua. Ut enim ad minim veniam, 
                    quis nostrud exercitation ullamco laboris nisi ut aliquip 
                    ex ea commodo consequat.</p>
            </div>     
        </div>
    </div>
</div> 
<div class="footer">
       <div class="footer__info">
           <div class="footer__header">Lets Talk!</div>
           <p class="footer__text">We are always open to discuss your project, 
               improve your online presence and help with your 
               UX/UI design challenges.</p>
               <div class="footer__contacts">
                   <div class="footer__title">
                       <p>Email me at</p>
                       <p>Call us</p>
                   </div>
                   <div class="footer__phone__text">
                       <p>contact@website.com</p>
                       <p>0927 6277 28525</p>
                   </div>
               </div>
       </div> 
</div>
{% endblock content %}

test_task_news/news_main/templates/news_main/add_news.html
{% extends 'news_main/base.html' %}
{% load static %}
{% block content %}
    <h1>Add news</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Создать" />
    </form>
{% endblock content %}

test_task_news/news_main/templates/news_main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock css %}
</head>
<body>
<div class="container">
    {% block header %}
    {% include 'news_main/includes/menu.html' %}
    {% endblock header %}
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

test_task_news/news_main/templates/news_main/contacts.html
{% extends 'news_main/base.html' %}
% load static %}
{% block content %}
<div class="content__info">
    <h2 class="info__header">Contact Us</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
        sed do eiusmod tempor incididunt ut labore.</p>
</div>
<div class="contacts">
    <ul class="contact">
        <li class="contact__info">
            <p class="contact__p">Адрес: Москва</p>
            <p class="contact__p">Телефон: 8-000-000-00-00</p>
        </li>
    </ul>
    <ul class="contact">
        <li class="contact__info">
            <p class="contact__p">Адрес: Москва</p>
            <p class="contact__p">Телефон: 8-000-000-00-00</p>
        </li>
    </ul>
</div>
{% endblock content %}

test_task_news/news_main/templates/news_main/delete_view.html
{% extends 'news_main/base.html' %}
% load static %}
{% block content %}
<div class="main">
    <form method="POST">
        {% csrf_token %}
        Are you want to delete this item ?
        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
    </form>
</div>

{% endblock content %}

test_task_news/news_main/templates/news_main/feedback.html
{% extends 'news_main/base.html' %}
% load static %}
{% block content %}
<form class="mainform">
    <p class="name">
        <input type="text" name="name" value="Имя">
    </p>
    <p class="email">
        <input type="text" name="email" value="name@example.com">
    </p>
    <p class="message">
        <textarea name="msg">Текст сообщения</textarea>
    <p class="send"><input type="submit" value="Отправить"></p>
    </p>
</form>
{% endblock content %}

test_task_news/news_main/templates/news_main/includes/menu.html
{% load static %}
<header class="header">
    <a href="{% url 'main:index' %}">
        <img src="{% static 'img/logo.png' %}" class="logo" alt="">
    </a>
    <div class="link__block">
        <div class="link"><a href="{% url 'main:index' %}">Главная</a></div>
        <div class="link"><a href="{% url 'main:news' %}">Новости</a></div>
        <div class="link"><a href="{% url 'main:contacts' %}">Контакты</a></div>
        <div class="link"><a href="{% url 'main:about' %}">О нас</a></div>
        <div class="link"><a href="{% url 'main:feedback' %}">Обратная связь</a></div>
        <div class="link"><a href="{% url 'main:news_add' %}">Добавить</a></div>
    </div>
</header>

test_task_news/news_main/templates/news_main/news.html
{% extends 'news_main/base.html' %}
% load static %}
{% block content %}
<div class="content">
    {% for new in news %}

    <div class="news">
        <h4 class="news__header">{{ new.title }}</h4>
        <p class="main__text">{{ new.description }}</p>
        <div class="news__date">
            <div class="news__date_created">Дата создания:{{ new.created_at|date:"M d, Y" }}</div>
            <div class="news__date_updated">Дата обновления:{{ new.updated_at|date:"M d, Y" }}</div>
            <div class="news__watch">Просмотры: {{ new.views }}</div>
        </div>
        <div class="news__links">
            <a class="news__first" href="{% url 'main:news_edit' new.pk %}">Редактирвать</a>
            <a href="{% url 'main:news_delete' new.pk %}">Удалить</a>
        </div>
        {% for comm in new.comment_set.all %}
        <div class="news__comment_block">
            <div class="comment">{{ comm.text }}</div>
            <div class="comment">{{ comm.created_at|date:"M d, Y" }}</div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock content %}

test_task_news/news_main/templates/news_main/update_news.html
{% extends 'news_main/base.html' %}
{% load static %}
{% block content %}
<h1>Edit news</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update"/>
</form>
{% endblock content %}